#mysql的配置信息
spring:
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/springboot
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver 
  application:
    name: sip-usercenter-service1
    
#mybatis扫描
mybatis:
  type-aliases-package: cn.it.usercenter
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
